#!/usr/bin/env bash
# Purpose: Configure docker daemon proxy (systemd path) and generate shell proxy env script.
# Related: scripts/proxy-env.sh, scripts/redroid-cluster.sh
set -euo pipefail

# Configure Docker daemon proxy and generate shell proxy exports script.
# Default proxy endpoint matches local tunnel setups.
PROXY_URL="${1:-http://127.0.0.1:10090}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_SCRIPT="$ROOT_DIR/scripts/proxy-env.sh"

echo "Using proxy: $PROXY_URL"

cat >"$ENV_SCRIPT" <<EOF
#!/usr/bin/env bash
# Generated by scripts/configure_docker_proxy.sh
export http_proxy=$PROXY_URL
export https_proxy=$PROXY_URL
export HTTP_PROXY=$PROXY_URL
export HTTPS_PROXY=$PROXY_URL

curl www.google.com
EOF
chmod +x "$ENV_SCRIPT"
echo "Wrote env script: $ENV_SCRIPT"

has_systemd=false
if command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]; then
  has_systemd=true
fi

if [[ "$has_systemd" != "true" ]]; then
  echo "WARN: systemd is not active (PID 1 is not systemd)."
  echo "Docker daemon proxy drop-in cannot be auto-applied in this environment."
  echo "For current shell, run: source $ENV_SCRIPT"
  echo "If you start dockerd manually, prepend proxy env vars:"
  echo "  HTTP_PROXY=$PROXY_URL HTTPS_PROXY=$PROXY_URL dockerd ..."
  exit 0
fi

mkdir -p /etc/systemd/system/docker.service.d
cat >/etc/systemd/system/docker.service.d/http-proxy.conf <<EOF
[Service]
Environment="HTTP_PROXY=$PROXY_URL"
Environment="HTTPS_PROXY=$PROXY_URL"
Environment="NO_PROXY=localhost,127.0.0.1"
EOF

echo "Wrote: /etc/systemd/system/docker.service.d/http-proxy.conf"
systemctl daemon-reload
systemctl restart docker
systemctl show --property=Environment docker | sed -n '1p'

echo "DONE"
echo "For current shell, run: source $ENV_SCRIPT"
