#!/usr/bin/env bash
# Purpose: Export shell proxy variables for pull/network operations (generated helper script).
# Related: scripts/configure_docker_proxy.sh, DOCKER_PROXY_URL in scripts/redroid-cluster.sh
# Generated by scripts/configure_docker_proxy.sh
export http_proxy=http://127.0.0.1:10090
export https_proxy=http://127.0.0.1:10090
export HTTP_PROXY=http://127.0.0.1:10090
export HTTPS_PROXY=http://127.0.0.1:10090

curl www.google.com
